### ISSUE TITLE
在运行datapostprocess4calibrate.py文件时出现错误

### ISSUE THREAD

**Issue by zhaoliyang1** [OuyangWenyu/hydromodel#23]
Traceback (most recent call last):
  File "G:\yanling\bysj\xinanj\hydro-model-xaj-master\hydro-model-xaj-master\hydromodel\data\data_postprocess.py", line 263, in <module>
    read_and_save_et_ouputs(one_model_one_hyperparam_setting_dir, fold=0)
  File "G:\yanling\bysj\xinanj\hydro-model-xaj-master\hydro-model-xaj-master\hydromodel\data\data_postprocess.py", line 226, in read_and_save_et_ouputs
    _, e_train = xaj(
  File "G:\yanling\bysj\xinanj\hydro-model-xaj-master\hydro-model-xaj-master\hydromodel\models\xaj.py", line 785, in xaj
    _q, _e, *w0, s0, fr0, qi0, qg0 = xaj(
  File "G:\yanling\bysj\xinanj\hydro-model-xaj-master\hydro-model-xaj-master\hydromodel\models\xaj.py", line 808, in xaj
    (r, rim, e, pe), w = generation(
  File "G:\yanling\bysj\xinanj\hydro-model-xaj-master\hydro-model-xaj-master\hydromodel\models\xaj.py", line 222, in generation
    eu, el, ed = calculate_evap(lm, c, wu0, wl0, prcp, pet)
  File "D:\miniconda\envs\xaj\lib\site-packages\numba\np\arraymath.py", line 3481, in where_impl
    raise ValueError("all inputs should have the same shape")
ValueError: all inputs should have the same shape

Process finished with exit code 1

**Comment by zhaoliyang1** [comment]
报错显示数输入应该是相同的shape

**Comment by OuyangWenyu** [comment]
已经跑完结果了么，能把结果文件夹截个图看一下么

**Comment by zhaoliyang1** [comment]
Amireux
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "OuyangWenyu/hydro-model-xaj"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月4日(星期四) 上午8:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OuyangWenyu/hydro-model-xaj] 在运行datapostprocess4calibrate.py文件时出现错误 (Issue #23)





 
已经跑完结果了么，能把结果文件夹截个图看一下么

**Comment by OuyangWenyu** [comment]
> Amireux ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "OuyangWenyu/hydro-model-xaj" ***@***.***&gt;; 发送时间:&nbsp;2023年5月4日(星期四) 上午8:27 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [OuyangWenyu/hydro-model-xaj] 在运行datapostprocess4calibrate.py文件时出现错误 (Issue #23) 已经跑完结果了么，能把结果文件夹截个图看一下么 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

邮件回复？我这边看不到图

**Comment by zhaoliyang1** [comment]
![b92f91fa66100182c88a561b3df69cc](https://user-images.githubusercontent.com/94788496/236142375-7ddfcc5a-a93c-4bf1-8a25-70779aef3113.png)

**Comment by OuyangWenyu** [comment]
这块我之前一直是按一个流域来弄的，后面率定和测试部分改了多流域的，但是这块忘了跟着改了。如果只是看预测结果的话，直接看basins_metrcis_test.csv那些文件就行了，这个我需要再改改。

**Comment by OuyangWenyu** [comment]
你更新一下代码，再试一下现在行不行了，应该是没有问题了

**Comment by OuyangWenyu** [comment]
已经改进了前后处理数据接口，可以根据新的readme来操作
